### ISSUE TITLE
Consider configuring Renovate to auto-merge certain PRs

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-project-template#349] opened 2023-03-21 11:41 UTC
Based on the discussion at #346, we should consider setting up Renovate to auto-merge certain types of PR.

To me, it should be:

* Patch and minor versions for GitHub actions.
* Patch versions for project dependencies.

@micronaut-projects/core-developers thoughts?

**Comment by melix** [comment] 2023-03-21 11:43
Sounds good to me.

**Comment by sdelamo** [comment] 2023-03-21 11:43
My experience is we get a lot of breaking changes in patch versions of project dependencies.

**Comment by graemerocher** [comment] 2023-03-21 11:44
the PR would have to pass CI

**Comment by sdelamo** [comment] 2023-03-21 11:46
> the PR would have to pass CI

the problem is sometimes the breaking changes are subtle. Upgrade to SLF4J mayor version which will disable logging. etc. 

Please, note that often manual merging will fail to catch those as well. 🤷🏻‍♂️

**Comment by melix** [comment] 2023-03-21 11:47
> Please, note that often manual merging will fail to catch those as well. 🤷🏻‍♂️

Absolutely, so for me there's no difference. As long as the PR passes CI, we should merge, and if there's a regression, fix, revert and add a test.

**Comment by alvarosanchez** [comment] 2023-03-21 11:48
> the PR would have to pass CI

_Automerging defaults to using Pull Requests (automergeType="pr"). In that case Renovate first creates a branch and associated Pull Request, and then automerges the PR on a subsequent run once it detects the PR's status checks are "green". If by the next run the PR is already behind the base branch it will be automatically rebased, because Renovate only automerges branches which are up-to-date and green_

**Comment by sdelamo** [comment] 2023-03-21 11:49
> > Please, note that often manual merging will fail to catch those as well. 🤷🏻‍♂️
> 
> Absolutely, so for me there's no difference. As long as the PR passes CI, we should merge, and if there's a regression, fix, revert and add a test.

ok, to me.

**Comment by wetted** [comment] 2023-03-21 15:27
Not everyone uses semantic versioning and I have encountered breaking changes with patch versions of dependencies. One thing we need to keep an eye on is where transitive dependencies update kotlin to 1.8.x or groovy to 4.x, which can mean breaking changes for Micronaut 3.x modules. While we can avoid the direct problem by only merging if CI is green, I found at least one case where the module didn't break, but another one that depends on it did.

**Comment by melix** [comment] 2023-03-21 15:54
>  found at least one case where the module didn't break, but another one that depends on it did.

Yes but technically speaking, if the build passes, would you have manually merged? I assume you would have.

**Comment by wetted** [comment] 2023-03-21 15:57
> > found at least one case where the module didn't break, but another one that depends on it did.
> 
> Yes but technically speaking, if the build passes, would you have manually merged? I assume you would have.

Correct, of course. But I wanted to point out it's something to be aware of.

**Closed** 2024-06-05 16:20 UTC
